### ISSUE TITLE
placeOrder: User or API does not exist

### ISSUE THREAD

**Issue by francestu96** [nomeida/hyperliquid#10]
I'm trying a simple **sdk.exchange.placeOrder()**, however I got the following error:
```
{
  status: 'err',
  response: 'L1 error: User or API Wallet 0x93848686e4cceb3e821cdb221d30884fed46db23 does not exist.'
}
```

This is the very simple code I used:
```
const privKey = "51c.....e44"
const sdk = new Hyperliquid(privKey, true);

const order = await sdk.exchange.placeOrder({
    coin: "BTC-PERP",
    is_buy: true,
    sz: 0.001,
    limit_px: 0,
    order_type: { trigger: { isMarket: true, triggerPx: "0", tpsl: "tp" } },
    reduce_only: false
});
```

I connected the corresponding wallet to [Hyperliquid testnet](https://app.hyperliquid-testnet.xyz/trade) and already deposited 100 mock USDC but I got the above error.
The weird thing is that, each time I make the **placeOrder()** call, **the API Wallet address always change** even with the same passed private key!

**Comment by edisontim** [comment]
hey @francestu96, I'm getting this as well, can I know how you got through?

**Comment by francestu96** [comment]
Well this was my situation.

First of all, I installed actually this npm package: @visvirial/hyperliquid

I than noticed it was a bit different from the code of this repo but, at
least, it was a working package.

By using that package and passing the "testnet" parameter as "true", this
will not actually got passed up to the final Hyperliquid API REST call.
Thus, if you try to open an order on testnet, it will actually try to open
in mainnet and, since I didn't use the wallet in mainnet, it will correctly
return that error.

This was my case, are you in the same one?

BTW I decided to gave up with the project untill the correct npm package is
released...

**Comment by francestu96** [comment]
Are you trying using testnet?

In this repo code it looked to me that the "testnet" parameter was
correctly managed.

If you are trying on testnet, have you claimed the mock USDC and deposited
on the platform with the same address you are trying to make the order from
the API?

**Comment by edisontim** [comment]
No I'm trying on mainnet on this repo, not the one you have. The one you have worked and you weren't getting this address error?

**Comment by francestu96** [comment]
Ok sorry but on mainnet I didn't try with any of the code and I cannot help
you.
It should work though this code since in testnet it actually worked.
Have you deposited the USDC into the platform before opening the order?

**Comment by edisontim** [comment]
oh that's odd, I'm trying to do a spotOrder. Were you trading spots or perps? 
This is very strange
Yeah I have usdc in my spot wallet

**Comment by francestu96** [comment]
I ve been able to successfully open a testnet ETH perp order.
No tries on spot on mainnet sorry
