### ISSUE TITLE
CommonJS Compatibility for NestJS

### ISSUE THREAD

**Issue by darkpaladi** [nomeida/hyperliquid#16]
### Description
The `hyperliquid` package currently lacks compatibility with CommonJS environments like NestJS, which uses CommonJS by default. This leads to runtime errors such as `SyntaxError: Cannot use import statement outside a module`.

### Expected Behavior
The package should provide a precompiled CommonJS build in addition to the existing ES Module format. For example:
- `"main": "./dist/index.cjs.js"` for CommonJS
- `"module": "./dist/index.esm.js"` for ES Modules

This is a common best practice for npm libraries to ensure broader compatibility.

### Suggested Fix
Use tools like TypeScript or Babel to generate both CommonJS and ES Module builds, and update the `package.json` to include both formats.

Thank you in advance!

**Comment by nomeida** [comment]
Hey, thanks for the suggestion. Had overlooked this!

**Comment by Keref** [comment]
It used to work though, I just updated the package and now I have the same issue

**Comment by Keref** [comment]
The version I use which works with require (luckily since I cant refactor the whole project to switch to modules, and the latest version breaks if typescript isnt installed) is ^1.2.2

**Comment by nomeida** [comment]
> The version I use which works with `require` is ^1.2.2
> 
> I think it comes from the commit [a98e4f7](https://github.com/nomeida/hyperliquid/commit/a98e4f70e2330a704ba2d92529b08ce6c31bb52d) that broke it by removing the dist/ directory that allow imports with require, not sure why, I dont understand what it achieves and the commit just says it removes everything with explanation

Oh, huh, will re-add it then if that's what makes it work.

I thought the NPM package created the ./dist files when deploying to NPM, so I deleted them from the github just to make the github cleaner.

Will re-add//remove dist from .gitignore

Thanks @Keref
