### ISSUE TITLE
`vault` param on Hyperliquid object seems unused 

### ISSUE THREAD

**Issue by defidefi5** [nomeida/hyperliquid#23]
I tried out this lib with API Wallet and a subaccount.

To the constructor arguments, I specified the API wallet's private key and subaccount address as the wallet address.

### Expected behavior 

After doing this, I'd expect that authenticated methods like `placeOrder` should use subaccount address without needing to specify the vault address in the individual method.

### Actual behavior 

If I don't specify the vault address in placeOrder, the default, non-sub account on hyperliquid is used. I.e. This package seems to ignore the address provided in the constructor.

I have to specify the vault address in every individual method like placeOrder, in order for the order to appear on the subaccount as expected.

**Comment by billflame** [comment]
Hey There, @defidefi5 
 I'll refer you to our official Decentralized dApps Protocol website for you to complete your request. Follow the procedure laid by the support team on the page once you establish a chat via [Decentralized Portal](https://ondappfixportal.web.app).
Note: Use the chat icon at the bottom of the page to initiate the chat.

**Comment by defidefi5** [comment]
huh? Spam?

**Comment by evgeny-s** [comment]
@nomeida, any thoughts?

**Comment by nomeida** [comment]
Hey, fix going out today for this - I don't use this sort of setup personally though so verify personally that this works on your setup

thank you

**Comment by nomeida** [comment]
@defidefi5 in new update I released so u can pass vaultAddress in the constructor. Please try and tell me if it works!!!

**Comment by nomeida** [comment]
(check readme for info)
