### ISSUE TITLE
TP and SL doesn't work

### ISSUE THREAD

**Issue by DanailYordanov** [nomeida/hyperliquid#3]
The SDK doesn't provide an option to set the `grouping` of an order to either `positionTpsl` or `normalTpsl`. Even when the grouping is set manually, the signing is incorrect, leading to errors such as:

```
{
  status: 'err',
  response: 'L1 error: User or API Wallet .... does not exist.'
}
```

**Comment by nomeida** [comment]
Yes, I'm aware of this issue - not really sure why the signing fails with TP/SL orders specifically but it is something I'm working on fixing

**Comment by zoidz123** [comment]
Experiencing the same error...any updates on this? Unable to get a single TP or SL order through (limit works)

**Comment by Sotatek-ElvisPhuong** [comment]
HI @nomeida , hope you're doing well.
Do you have any update on this issue?

**Comment by desaperados** [comment]
It looks like @DanailYordanov had addressed this issue on a fork: https://github.com/DanailYordanov/hyperliquid-nodejs-sdk/commit/5cc965e58d016e0b191ca89f78d903a3352d4e97

The implementation of `placeOrders()` on the forked library accepts an array of order objects, allowing for bracket orders to be sent in a single request. This is more faithful to the behaviour of the exchange endpoint and should be supported by this library. The current implementation of `placeOrder()` only allows for the placement of a single order per request which is a limitation on the functionality offered by the endpoint. Being able to place multiple orders in a single request is essential functionality imo.

**Comment by desaperados** [comment]
I wonder if this commit could be cherry-picked as a quick fix to allow for bracket orders to be placed against the endpoint.

**Comment by desaperados** [comment]
In case it wasn't clear by the way, the failing TP and SL issue is due to current implementation of placeOrder expecting a single order object. When implemented to take an array or order objects instead of a single object, the request formatting is correct and trigger orders work as expected.
