### ISSUE TITLE
[SCAM??] Why did you set referrer in this method?

### ISSUE THREAD

**Issue by evgeny-s** [nomeida/hyperliquid#32]
[Method](https://github.com/nomeida/hyperliquid/blob/a2c44391533bcc55d96bd884f67768636bb23302/src/rest/exchange.ts#L75)

**Comment by evgeny-s** [comment]
It looks like a scam

**Comment by evgeny-s** [comment]
Now, I can't reset it...
<img width="364" alt="image" src="https://github.com/user-attachments/assets/dac50964-1636-4755-a849-27e0be76f64f" />

**Comment by nomeida** [comment]
I asked the Hyperliquid team about this and they were fine with it

**Comment by evgeny-s** [comment]
Who exactly from the Hyperliquid team has allowed you to do this? This is ridiculous.

**Comment by nomeida** [comment]
Been talking with Xulian and he said this is fine.

If you don’t believe me you can always DM him privately to confirm, you can find him in the HL discord.

**Comment by nomeida** [comment]
@evgeny-s 

Been talking with Xulian and he said this is fine.

If you don’t believe me you can always DM him privately to confirm, you can find him in the HL discord.

**Comment by desaperados** [comment]
I agree that this is not a good look - especially given that this is the only node library listed in the official Hyperliquid documentation. The fact that the maintainer of the library is collecting referral fees should be explicitly stated in the README and the Hyperliquid documentation should be updated to list alternative node libraries [such as this](https://github.com/nktkas/hyperliquid), which is arguably better implemented and with more comprehensive test coverage.

It is of course entirely up to the @nomdia as to whether or not a referral fee is collected but it needs to be transparently communicated in order that api users (and contributors) have the choice as to whether or not they want to use the library on those terms.

I for one would not have contributed to the maintenance of this library had I noticed this prior. It is not in the spirit of opensource development and I'm guessing will be quickly forked out or made redundant.
