### ISSUE TITLE
L1 error keeps triggering when the exchange API is used

### ISSUE THREAD

**Issue by xfinalangelx** [nomeida/hyperliquid#4]
Hi there, I have been encountering issues in NextJS when trying to place an order on the test net where it returns

```
{
    "status": "err",
    "response": "L1 error: User or API Wallet <address> does not exist."
}
```

where the address changes randomly everytime when it was triggered, and below is my code which is very similar to the snipper you provided in the README docs

```
// Import the Hyperliquid SDK
const { Hyperliquid } = require("hyperliquid");


export default async function handler(req, res) {
  // Initialize the Hyperliquid SDK with your private key
  const sdk = new Hyperliquid(
    <private_key>,
    true
  );

  sdk.exchange
    .placeOrder({
      coin: "BTC-PERP",
      is_buy: true,
      sz: 0.01,
      limit_px: 50000,
      order_type: { limit: { tif: "Gtc" } },
      reduce_only: false,
    })
    .then((placeOrderResult: any) => {
      console.log(placeOrderResult);
      // Return the data as a JSON response
      res.status(200).json(placeOrderResult);
    })
    .catch((error: any) => {
      console.error("Error placing order:", error);
    });
}
```
Do let me know if there's anything I did wrong or if it's a problem from my side because as you can see from my attachment, my testnet account did have balance and I am not sure why this occurs, Thanks in advance! :)

<img width="1438" alt="image" src="https://github.com/user-attachments/assets/fc9c4d81-680f-4cb4-9e55-54930834f100">

**Comment by GuihaiHU** [comment]
I met the same problem.And I found that, when I run my code in mainnet, everything runs well.
Is it something wrong with TestNet?

**Comment by GuihaiHU** [comment]
I found the bug. I will fix and commit it soon
<img width="752" alt="image" src="https://github.com/user-attachments/assets/be18207a-5123-4408-b843-2e1a1de0ab4c">

**Comment by nomeida** [comment]
@GuihaiHU Thank you, I've been absent for a bit will merge your fix once I'm home

**Comment by allenchuang** [comment]
@GuihaiHU were you able to get it running in NextJS? i keep getting 

`"Module not found: Can't resolve 'hyperliquid'"`

can you share how you resolve this?
