### ISSUE TITLE
placeOrder is missing vaultAddress

### ISSUE THREAD

**Issue by andershermansen** [nomeida/hyperliquid#5]
The hyperliquid API documentation contains vaultAddress on the body of the Place an order API
Ref: https://hyperliquid.gitbook.io/hyperliquid-docs/for-developers/api/exchange-endpoint#place-an-order

It's missing in placeOrder in this SDK

**Comment by nomeida** [comment]
Will address this coming few days, missed this as I was creating the code as I don't use Vaults myself

**Comment by nomeida** [comment]
Has been added, check readme for more info
