### ISSUE TITLE
marketClose, closeAllPositions and cancelAllOrders using wrong address

### ISSUE THREAD

**Issue by andershermansen** [nomeida/hyperliquid#7]
I tried to use marketClose and closeAllPositions but it can not find the position.

It seems the info API is called with the address of the API key:
https://github.com/nomeida/hyperliquid/blob/4f4cf9621c63db12a54f9c88fada51ceb1683f39/src/rest/custom.ts#L122

From the documentation at https://hyperliquid.gitbook.io/hyperliquid-docs/for-developers/api/nonces-and-api-wallets#api-wallets

> Note that API wallets are only used to sign. To query the account data associated with a master or sub-account, you must pass in the actual address of that account. A common pitfall is to use the agent wallet which leads to an empty result.

It was easy enough to just implement what you had done in custom api myself and use the info and exchange API directly with the address I wanted. Just wanted to let you know about this issue. Thanks for a good and easy library!

**Comment by nomeida** [comment]
Hey!

I created this SDK before API wallets were available haha, will amend the code to accomodate for API wallets as well

**Comment by nomeida** [comment]
Rolling out the fix for this today, you'll be able to pass your account/wallet address in the instance creation like this:

`const sdk = new Hyperliquid(pk, false, address);

sdk.custom.marketClose("BTC-PERP").then(console.log).catch(console.error);
`
