### ISSUE TITLE
Published package in npm does not contain the build code but only the source code

### ISSUE THREAD

**Issue by alex1712** [nomeida/hyperliquid#8]
Maybe I am wrong but I think in the published package on npm, the dist folder should be the one there  (https://www.npmjs.com/package/hyperliquid?activeTab=code) I tried as it is now and for me is not working properly

**Comment by francestu96** [comment]
Same here. I can confirm the npm package is not working

**Comment by Oni-giri** [comment]
Same issue here

**Comment by desaperados** [comment]
I wasn't aware of this issue at the time but I realise that I addressed this in a housekeeping commit on [this PR](https://github.com/nomeida/hyperliquid/pull/15).

The `dist` directory was not listed in package.json`files` and not being included by the npm build process. This PR includes the change to `package.json` to ensure that the `dist` directory will now be included in the build output.

**Comment by azflin** [comment]
maintainer pls merge dat fix

**Comment by nomeida** [comment]
Fixing today, sorry been away
